[project]
name = "fantasyhelper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "google-auth-oauthlib>=1.4.1",
    "gspread>=6.2.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "jupyter-black>=0.4.0",
    "nhl-api-py>=3.0.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pyyaml>=6.0.2",
    "tables>=3.10.2",
    "yahoofantasy>=1.4.8",
    "yfpy>=16.0.3",
]

[project.scripts]
fantasyhelper = "fantasyhelper.cli:main"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "fantasyhelper",
]
